apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-dep1
  name: ashu-dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-dep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-dep1
    spec:
      imagePullSecrets: # calling secret 
      - name: ashu-reg-cred # we already created it 
      containers:
      - image: aksashutoshh.azurecr.io/webapp:version1
        name: webapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
